- name: install prometheus
  hosts: all
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_targets: {}
    prometheus_scrape_configs:
      - job_name: "prometheus"
        metrics_path: "{{ prometheus_metrics_path }}"
        static_configs:
          - targets:
              - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090 "
      - job_name: "file_sd"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/*.yml"
              - "{{ prometheus_config_dir }}/file_sd/*.json"
      - job_name: "consul_sd"
        consul_sd_configs:
          - server: localhost:8500

  tags:
    - ape_prometheus

- name: install grafana
  hosts: all
  roles:
  - cloudalchemy.grafana
  vars:
    grafana_security:
      admin_user: admin
      admin_password: admin
    grafana_datasources:
      - name: prometheus-ape
        type: prometheus
        access: proxy
        url: 'http://localhost:9090'
        basicAuth: false
    grafana_dashboards:
      - dashboard_id: 1860
        revision_id: 23
        datasource: prometheus-ape
    grafana_dashboards_dir: "{{ lookup('env', 'PWD') }}/dashboards"
  tags:
    - ape_grafana

- name: install consul
  hosts: all
  become: true
  vars:
    consul_group_name: all
    consul_client_address: 0.0.0.0
    consul_encrypt_enable: false
    consul_node_role: bootstrap
  roles:
  - ansible-consul
  tags: ape_consul

- name: install ape_sqs
  hosts: all
  vars:
    project_path: "{{ lookup('env', 'PWD') }}"
    meta_json_file: "{{ lookup('env', 'PWD') }}/meta.json"
    private_key_path: "{{ lookup('env', 'PWD') }}/keys"
  roles:
    - ape_sqs
  tags:
    - ape_sqs