---
- import_tasks: preflight.yml
  tags:
    - ape_install
    - ape_configure
    - ape_run

- import_tasks: install.yml
  become: true
  when:
     not  __ape_venv_is_installed.stat.exists
  tags:
    - ape_install


- import_tasks: configure.yml
  become: true
  tags:
    - ape_configure

- name: Ensure ape sqs is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: ape_sqs
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - ape_run
