---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    jmx_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Check if ape-venv is installed
  stat:
    path: "{{ _ape_venv_dir }}/{{_ape_venv_name}}/pyvenv.cfg"
  register: __ape_venv_is_installed
  check_mode: false
  tags:
    - ape_venv_install
