{
 "title": "HDFS - NameNode",
 "tags": [
  "Amazon EMR",
  "HDFS",
  "prometheus-ape"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(hdfs_namenode_capacity_total, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(hdfs_namenode_capacity_total_gb{job=~\"$job\"}, cluster_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(hdfs_namenode_capacity_total_gb{job=~\"$job\", cluster_id=~'$cluster'}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up {job=\"$job\", cluster_id=~'$cluster', instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "HDFS Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdfs_namenode_capacity_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"})"
    }
   ]
  },
  {
   "title": "Block Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdfs_namenode_block_capacity {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"})"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdfs_namenode_num_live_data_nodes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"})"
    }
   ]
  },
  {
   "title": "Dead Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdfs_namenode_num_dead_data_nodes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"})"
    }
   ]
  },
  {
   "title": "Files",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdfs_namenode_files_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"})"
    }
   ]
  },
  {
   "title": "Total Load (Number of Concurrent File Access)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hdfs_namenode_total_load {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"FSNamesystem\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Checkpoint Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(hdfs_namenode_last_checkpoint_time {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Volume Failures",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdfs_namenode_volume_failures_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"})"
    }
   ]
  },
  {
   "title": "Corrupt Blocks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdfs_namenode_corrupt_blocks {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"})"
    }
   ]
  },
  {
   "title": "Missing Blocks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdfs_namenode_missing_blocks {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Blocks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdfs_namenode_under_replicated_blocks {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"})"
    }
   ]
  },
  {
   "title": "Disk Capacity Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "hdfs_namenode_capacity_used {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}/ hdfs_namenode_capacity_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Capacity Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "hdfs_namenode_blocks_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}/hdfs_namenode_block_capacity {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "File Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(hdfs_namenode_total_file_ops {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"NameNodeActivity\"} [$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hdfs_namenode_transactions_num_ops {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"NameNodeActivity\"} [$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "HDFS Capacity Utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_capacity_used {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}/ hdfs_namenode_capacity_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Used HDFS Capacity",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_capacity_used {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Remaining HDFS Capacity",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_capacity_remaining {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Block Capacity Utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_blocks_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}/hdfs_namenode_block_capacity {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Allocated Blocks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_blocks_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Free Blocks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_block_capacity {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"} - hdfs_namenode_blocks_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Corrupted Blocks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_corrupt_blocks {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Missing Blocks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_missing_blocks{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Excess Blocks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_excess_blocks{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Add Blocks Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(hdfs_namenode_add_block_ops {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\"} [$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Under Replicated Blocks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_under_replicated_blocks{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scheduled Replication Blocks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_scheduled_replication_blocks {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Pending Replication Blocks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_pending_replication_blocks {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Missing Replication Blocks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_missing_replicated_blocks {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Corrupt Replication Blocks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hdfs_namenode_corrupt_replicated_blocks {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"NameNode\", kind=\"FSNamesystem\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}