{
 "title": "HDFS - DataNode",
 "tags": [
  "Amazon EMR",
  "HDFS",
  "prometheus-ape"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(hdfs_datanode_capacity, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(hdfs_datanode_capacity{job=~\"$job\"}, cluster_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(hdfs_datanode_capacity{job=~\"$job\", cluster_id=~'$cluster'}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "HDFS Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdfs_datanode_capacity {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"FSDatasetState\",fsdatasetid=''})"
    }
   ]
  },
  {
   "title": "Failed Volumes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hdfs_datanode_num_failed_volumes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"DataNode\", kind=\"FSDatasetState\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Remaining Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "hdfs_datanode_remaining {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"FSDatasetState\", fsdatasetid=''}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-hdfs_datanode_remaining {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"FSDatasetState\", fsdatasetid=''}/ hdfs_datanode_capacity {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"FSDatasetState\", fsdatasetid=''}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latest Volume Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(hdfs_datanode_last_volume_failure_date {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hdfs_datanode_bytes_written {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"DataNodeActivity\"} [$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hdfs_datanode_bytes_read {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"DataNodeActivity\"} [$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hdfs_datanode_datanode_network_errors {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"DataNodeActivity\"} [$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Capacity Utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1-hdfs_datanode_remaining {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"FSDatasetState\", fsdatasetid=''}/ hdfs_datanode_capacity {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"FSDatasetState\", fsdatasetid=''}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Used Disk Capacity",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "hdfs_datanode_dfs_used {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"FSDatasetState\", fsdatasetid=''}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Remaining Disk Capacity",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "hdfs_datanode_remaining {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"FSDatasetState\", fsdatasetid=''}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Writes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(hdfs_datanode_bytes_written {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"DataNodeActivity\"} [$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Reads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(hdfs_datanode_bytes_read {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"DataNodeActivity\"} [$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write Block Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(hdfs_datanode_blocks_written {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"DataNodeActivity\"} [$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Read Block Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(hdfs_datanode_blocks_read {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"DataNodeActivity\"} [$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Replication Block Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(hdfs_datanode_blocks_replicated {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"DataNodeActivity\"} [$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Remove Block Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(hdfs_datanode_blocks_removed {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"DataNodeActivity\"} [$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Volumes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hdfs_datanode_num_failed_volumes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"FSDatasetState\", fsdatasetid=''}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(hdfs_datanode_datanode_network_errors {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"DataNodeActivity\"} [$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Send Data Packets Blocked on Network",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(hdfs_datanode_send_data_packet_blocked_on_network_nanos_num_ops {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', kind=\"DataNodeActivity\"} [$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Packet Wait Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "hdfs_datanode_send_data_packet_blocked_on_network_nanos_avg_time  {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"DataNode\", kind=\"DataNodeActivity\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Packet Transfer Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "hdfs_datanode_send_data_packet_transfer_nanos_avg_time {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', role=\"DataNode\", kind=\"DataNodeActivity\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}