{
 "title": "YARN - Queues",
 "tags": [
  "Amazon EMR",
  "YARN",
  "prometheus-ape"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(yarn_resourcemanager_queue_apps_running, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(yarn_resourcemanager_queue_apps_running{job=~\"$job\"}, cluster_id)"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "label_values(yarn_resourcemanager_queue_apps_running{job=~\"$job\", cluster_id=~'$cluster'}, queue)"
   },
   {
    "name": "child_queue",
    "label": "Child Queue",
    "query": "label_values(yarn_resourcemanager_queue_apps_running{job=~\"$job\", cluster_id=~'$cluster', queue=\"$queue\"}, child_queue)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Absolute Configured Max Capacity",
   "type": "singlestat",
   "description": "Absolute  Max Capacity of the queue relative to the cluster.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "yarn_resourcemanager_queue_max_absolute_capacity {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
     "legendFormat": "{{queue}}_{{child_queue}}"
    }
   ]
  },
  {
   "title": "Absolute Configured Capacity",
   "type": "singlestat",
   "description": "Minimum absolute capacity of the queue relative to the cluster.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "yarn_resourcemanager_queue_guaranteed_absolute_capacity {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
     "legendFormat": "{{queue}}_{{child_queue}}"
    }
   ]
  },
  {
   "title": "Configured Max Capacity",
   "type": "singlestat",
   "description": "Maximum capacity configured relative to the parent.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "yarn_resourcemanager_queue_max_capacity {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
     "legendFormat": "{{queue}}_{{child_queue}}"
    }
   ]
  },
  {
   "title": "Configured Capacity",
   "type": "singlestat",
   "description": "Minimum capacity of the queue relative to the parent.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "yarn_resourcemanager_queue_guaranteed_capacity {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
     "legendFormat": "{{queue}}_{{child_queue}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "singlestat",
   "description": "Minimum capacity of the queue relative to the parent.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(yarn_resourcemanager_queue_active_users {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"})",
     "legendFormat": "{{queue}}_{{child_queue}}"
    }
   ]
  },
  {
   "title": "Absolute Used Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "yarn_resourcemanager_queue_absolute_used_capacity {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
     "legendFormat": "{{queue}}_{{child_queue}}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "yarn_resourcemanager_queue_used_capacity {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
     "legendFormat": "{{queue}}_{{child_queue}}"
    }
   ]
  },
  {
   "title": "Active Applications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yarn_resourcemanager_queue_active_applications {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
     "legendFormat": "{{queue}}_{child_queue}}"
    }
   ]
  },
  {
   "title": "Apps Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Apps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_apps_running {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Completed Apps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_apps_completed {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Failed Apps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_apps_failed {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Pending Apps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_apps_pending {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Submitted Apps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_apps_submitted {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Killed Apps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_apps_killed {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated Containers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_allocated_containers {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Pending Containers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_pending_containers {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Reserved Containers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_reserved_containers {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "VCores Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_allocated_vcores {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"} + yarn_resourcemanager_queue_available_vcores {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"} + yarn_resourcemanager_queue_pending_vcores {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"} + yarn_resourcemanager_queue_reserved_vcores {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Available VCores",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_available_vcores {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Allocated VCores",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_allocated_vcores {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Pending VCores",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_pending_vcores {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Reserved VCores",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_reserved_vcores {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
     "format": "decmbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_max_capacity_mb {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 17 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_available_mb {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1-yarn_resourcemanager_queue_available_mb {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}/yarn_resourcemanager_queue_max_capacity_mb {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Allocated Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_allocated_mb {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Pending Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_pending_mb {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Reserved Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_reserved_mb {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Master Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
     "format": "decmbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_amresource_limit_mb {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}"
      }
     ]
    },
    {
     "title": "AM Used Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 3, "y": 6 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_used_amresource_mb {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "AM Used VCores",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_used_amresource_vcores {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "AM Container Allocation Delay",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_app_attempt_first_container_allocation_delay_avg_time {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}",
       "legendFormat": "{{queue}}_{{child_queue}}"
      }
     ]
    },
    {
     "title": "Total Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "yarn_resourcemanager_queue_amresource_limit_vcores {job=\"$job\", cluster_id=~'$cluster', queue=\"$queue\", child_queue=\"$child_queue\"}"
      }
     ]
    }
   ]
  }
 ]
}