{
 "title": "YARN - Resource Manager",
 "tags": [
  "Amazon EMR",
  "YARN",
  "prometheus-ape"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(yarn_resourcemanager_queue_apps_running, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(yarn_resourcemanager_queue_apps_running{job=~\"$job\"}, cluster_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(yarn_resourcemanager_queue_apps_running{job=~\"$job\", cluster_id=~'$cluster'}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (job) (yarn_resourcemanager_clustermetrics_num_active_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} + yarn_resourcemanager_clustermetrics_num_decommissioning_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} + yarn_resourcemanager_clustermetrics_num_lost_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} + yarn_resourcemanager_clustermetrics_num_rebooted_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} + yarn_resourcemanager_clustermetrics_num_shutdown_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} + yarn_resourcemanager_clustermetrics_num_unhealthy_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (job) (yarn_resourcemanager_clustermetrics_num_active_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} )"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job, instance) (yarn_resourcemanager_queue_available_mb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_available_mb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})/sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_max_capacity_mb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (job) (yarn_resourcemanager_queue_max_capacity_mb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total VCores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (job) (yarn_resourcemanager_queue_allocated_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''} +  yarn_resourcemanager_queue_available_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''}+ yarn_resourcemanager_queue_pending_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''} +  yarn_resourcemanager_queue_reserved_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})"
    }
   ]
  },
  {
   "title": "Available VCores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_available_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VCores Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_available_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})/sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_allocated_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''} + yarn_resourcemanager_queue_available_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''} + yarn_resourcemanager_queue_pending_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''} + yarn_resourcemanager_queue_reserved_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running Apps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_apps_running {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Node Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (yarn_resourcemanager_clustermetrics_num_active_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} + yarn_resourcemanager_clustermetrics_num_decommissioning_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} + yarn_resourcemanager_clustermetrics_num_lost_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} + yarn_resourcemanager_clustermetrics_num_rebooted_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} + yarn_resourcemanager_clustermetrics_num_shutdown_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} + yarn_resourcemanager_clustermetrics_num_unhealthy_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yarn_resourcemanager_clustermetrics_num_active_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} ",
     "legendFormat": "{{instance}}_active"
    },
    {
     "expr": "yarn_resourcemanager_clustermetrics_num_unhealthy_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} ",
     "legendFormat": "{{instance}}_unhealthy"
    },
    {
     "expr": "yarn_resourcemanager_clustermetrics_num_lost_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} ",
     "legendFormat": "{{instance}}_lost"
    },
    {
     "expr": "yarn_resourcemanager_clustermetrics_num_decommissioning_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} ",
     "legendFormat": "{{instance}}_decommissioning"
    },
    {
     "expr": "yarn_resourcemanager_clustermetrics_num_decommissioned_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} ",
     "legendFormat": "{{instance}}_decommissioned"
    },
    {
     "expr": "yarn_resourcemanager_clustermetrics_num_rebooted_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} ",
     "legendFormat": "{{instance}}_rebooted"
    },
    {
     "expr": "yarn_resourcemanager_clustermetrics_num_shutdown_nms {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} ",
     "legendFormat": "{{instance}}_shutdown"
    }
   ]
  },
  { "title": "Application Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Running Apps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_apps_running {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Completed Apps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_apps_completed {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Apps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_apps_failed {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending Apps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_apps_pending {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Submitted Apps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_apps_submitted {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Killed Apps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (yarn_resourcemanager_queue_apps_killed {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Applications by Running Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yarn_resourcemanager_queue_running_0 {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''}",
     "legendFormat": "{{instance}}: under 1 hour"
    },
    {
     "expr": "yarn_resourcemanager_queue_running_60 {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''}",
     "legendFormat": "{{instance}}: between 1 and 5 hours"
    },
    {
     "expr": "yarn_resourcemanager_queue_running_300 {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''}",
     "legendFormat": "{{instance}}: between 5 and 24 hours"
    },
    {
     "expr": "yarn_resourcemanager_queue_running_1440 {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''}",
     "legendFormat": "{{instance}}: above 24 hours"
    }
   ]
  },
  { "title": "Container Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Allocated Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_allocated_containers {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_pending_containers {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reserved Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_reserved_containers {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "VCores Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Total VCores",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_allocated_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''} + yarn_resourcemanager_queue_available_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''} + yarn_resourcemanager_queue_pending_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''} + yarn_resourcemanager_queue_reserved_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''}))"
    }
   ]
  },
  {
   "title": "Available VCores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_available_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Allocated VCores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_allocated_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending VCores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_pending_vcores{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reserved VCores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_reserved_vcores{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Memory Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 60 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum by(job, cluster, instance) (yarn_resourcemanager_queue_max_capacity_mb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 60 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job, instance) (yarn_resourcemanager_queue_available_mb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 60 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_available_mb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})/sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_max_capacity_mb {job=\"$job\", cluster_id=~'$cluster',instance=~'$instance', child_queue=''}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_allocated_mb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_pending_mb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reserved Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_reserved_mb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Application Master Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Memory Limit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 73 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum by(job, cluster_id, instance, child_queue) (yarn_resourcemanager_queue_amresource_limit_mb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue!=\"\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AM Used Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 73 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_used_amresource_mb  {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AM Used VCores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_queue_used_amresource_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue=''})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VCores Limit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 76 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum by(job, cluster_id, instance, child_queue) (yarn_resourcemanager_queue_amresource_limit_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', child_queue!=\"\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Allocation Delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_clustermetrics_amlaunch_delay_avg_time {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Allocation Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (rate(yarn_resourcemanager_clustermetrics_amcontainer_allocation_delay_num_ops{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Registration Delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_clustermetrics_amregister_delay_avg_time {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Registration Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (rate(yarn_resourcemanager_clustermetrics_amregister_delay_num_ops{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Launch Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (rate(yarn_resourcemanager_clustermetrics_amlaunch_delay_num_ops{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Launch Delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by(job, cluster_id, instance) (yarn_resourcemanager_clustermetrics_amlaunch_delay_avg_time{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}